### ISSUE TITLE
Buttons in ContextMenu Not Toggling

### ISSUE THREAD

**Issue by Ohmstyle64** [yiochen/CSE381#79]
Somtimes when a ship is moving you cannot build a second ship.

**Comment by yiochen** [comment]
It might be because the size of the ship button is actually pretty small. It's a small square inside the circular slider. For `onclick` to get called, mouse has to be inside the box from `mouse down` until `mouse up`. If mouse leave in the mid way, onclick wont be called. I will look forward to increase the button size
